# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Github Page Deploy Workflow

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
# Deployment job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

